CC=gcc
CFLAGS=-I

hellomake: hellomake.c hellofunc.c
	gcc -o hellomake hellomake.c hellofunc.c -I.

# hellomakevars: hellomake.o hellofunc.o
# 	$(CC) -o hellomake hellomake.c hellofunc.c

# hellomake1: hellomake.o hellofunc.o
# 	$(CC) -o hellomake hellomake.o hellogunc.o